  
  - name: Check if iso files are exist
    file: path={{storage_nfs_mount_point}}/iso/{{item}}
    ignore_errors: yes
    register: iso_exist
    with_items:
       __iso_files

  - name: set concurrent path
    local_action: command pwd
    register: pwd
    
  - debug: var=iso_exist
    
  - name: Create copy.sh which will copy all iso files to storage server
    local_action: template src=copy.sh.j2 dest="{{pwd.stdout}}/copy.sh" mode=0777
  
  - name: execute copy.sh file to copy iso file asynchronally
    shell: "{{pwd.stdout}}/copy.sh"
    delegate_to: localhost
    async: 300
    poll: 0
    register: iso_copy
    when: iso_exist.msg != "All items completed"
  
