
  - include: ./disk.yaml
  - include: ./copy_iso.yaml

  - name: Check async copy.sh status
    async_status: jid={{ iso_copy.ansible_job_id }}
    register: iso_copy_complete
    until: iso_copy_complete.finished
    retries: 30
    delegate_to: localhost
    when: iso_exist.msg != "All items completed"

  - include: ./temp_repos.yaml
  - include: ./selinux.yaml
  - include: ./network.yaml
  - include: ./services.yaml
  - include: ./nfs.yaml
  - include: ./iscsi.yaml
  - include: ./lvm.yaml

  - include: ./clean.yaml

  
