

   - name: copy storage network ifcfg file to storage machine
     template: src=ifcfg-storage.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{storage_storage_network_interface}}
     register: storage_network

   - name: restart network service
     service: name=network state=restarted
     when: storage_network.changed == true 
