- hosts: storages
  gather_facts: false

  pre_tasks:
  - name: set concurrent path
    local_action: command pwd
    register: pwd
    tags: test

  - debug: var=iso_exist

  - name: set_facts - pwd_path
    set_fact:
       pwd_path: "{{pwd.stdout}}"  
    tags: test

  roles:
    - { role: rhev_storage, tags: storage } 

- hosts: managers
  gather_facts: false

  roles:
    - { role: rhev_manager, tags: manager } 

- hosts: hypervisors
  gather_facts: false
  roles:
    - { role: rhev_hypervisor, tags: hypervisor } 

