- name: Configure MariaDB
  hosts: centos7
  tasks:    
  - name: install MariaDB
    yum: name=mariadb state=installed 
  - name: install MariaDB server
    yum: name=mariadb-server state=installed 
  - name: Calculate InnoDB buffer pool size 
    set_fact: innodb_buffer_pool_size_mb="{{ ansible_memtotal_mb / 2 }}"   
  - name: Configure MariaDB    
    template: src=template/my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0644
    notify: restart mariadb 
  - name: Start MariaDB     
    service: name=mariadb state=started enabled=yes    
  
  handlers:     
   - name: restart mariadb    
     service: name=mariadb state=restarted   
