  - name: Check if iptables is installed
    yum: name=iptables
    register: iptables_installed

  - name: Disable/stop iptables
    service: name=iptables state=stopped enabled=no
    tags: services
    register: iptables_stopped
    ignore_errors: yes
    when: iptables_installed.rc == 0

  - name: Check chkconfig of iptables
    shell: chkconfig --list |grep iptables
    tags: services
    ignore_errors: yes
    when: iptables_installed.rc == 0
